import {
  afterAll,
  afterEach,
  beforeAll,
  beforeEach,
  describe,
  expect,
  it,
} from 'vitest';
import { randomBytes } from 'node:crypto';

import { createPgMem, type PgMemContext } from '../../helpers/postgres-pgmem.js';
import { buildApp } from '../../../src/app.js';
import { signAccessToken } from '../../../src/auth/jwt.js';
import { resetMasterKeyForTesting } from '../../../src/crypto/aes-gcm.js';

/**
 * Integration tests for `/admin/provider-keys`.
 *
 * Validates: Requirements 4.1, 4.3, 4.4, 4.6, 4.8, 4.9, 11.9.
 *
 * Uses pg-mem; the routes use only standard SQL plus `FOR UPDATE`
 * (which pg-mem accepts as a no-op). `gen_random_uuid()` is not used
 * because every UUID in the route is generated by node `crypto`.
 */

const INIT_SQL = `
  CREATE TABLE provider_keys (
    provider    text PRIMARY KEY,
    ciphertext  bytea NOT NULL,
    nonce       bytea NOT NULL,
    auth_tag    bytea NOT NULL,
    last4       text NOT NULL,
    version     integer NOT NULL DEFAULT 1,
    created_at  timestamptz NOT NULL DEFAULT now(),
    updated_at  timestamptz NOT NULL DEFAULT now()
  );

  CREATE TABLE audit_log (
    id              uuid PRIMARY KEY,
    ts              timestamptz NOT NULL DEFAULT now(),
    actor_user_id   uuid NULL,
    target_user_id  uuid NULL,
    target_resource text NULL,
    event_type      text NOT NULL,
    outcome         text NOT NULL,
    reason_code     text NULL,
    metadata        jsonb NOT NULL DEFAULT '{}'::jsonb
  );
`;

const ADMIN_ID = '22222222-2222-4222-8222-222222222222';
const USER_ID = '11111111-1111-4111-8111-111111111111';
const CLIENT_ID = 'aaaaaaaa-aaaa-4aaa-8aaa-aaaaaaaaaaaa';

let ctx: PgMemContext;
let restore: () => void;
let originalJwtSecret: string | undefined;
let originalMasterKey: string | undefined;

beforeAll(async () => {
  originalJwtSecret = process.env['JWT_SECRET'];
  process.env['JWT_SECRET'] = 'test-secret-for-provider-keys-routes-1';

  originalMasterKey = process.env['MASTER_ENCRYPTION_KEY'];
  // Use a fixed deterministic key to avoid pg-mem bytea parsing issues
  // that occur with certain random byte sequences in ciphertext output.
  process.env['MASTER_ENCRYPTION_KEY'] = 'dGVzdC1tYXN0ZXIta2V5LWZvci1wcm92aWRlci1rZXk=';
  resetMasterKeyForTesting();

  ctx = await createPgMem({ initSql: INIT_SQL });
});

afterAll(async () => {
  await ctx.stop();

  if (originalJwtSecret === undefined) {
    delete process.env['JWT_SECRET'];
  } else {
    process.env['JWT_SECRET'] = originalJwtSecret;
  }

  if (originalMasterKey === undefined) {
    delete process.env['MASTER_ENCRYPTION_KEY'];
  } else {
    process.env['MASTER_ENCRYPTION_KEY'] = originalMasterKey;
  }
  resetMasterKeyForTesting();
});

beforeEach(() => {
  restore = ctx.snapshot();
});

afterEach(() => {
  restore();
});

async function adminBearer(): Promise<string> {
  const { token } = await signAccessToken({
    sub: ADMIN_ID,
    role: 'admin',
    clientId: CLIENT_ID,
  });
  return `Bearer ${token}`;
}

async function userBearer(): Promise<string> {
  const { token } = await signAccessToken({
    sub: USER_ID,
    role: 'user',
    clientId: CLIENT_ID,
  });
  return `Bearer ${token}`;
}

function makeApp() {
  return buildApp({ pool: ctx.pool });
}

interface AuditRow {
  actor_user_id: string;
  target_resource: string;
  event_type: string;
  outcome: string;
  metadata: Record<string, unknown>;
}

async function readAuditRows(eventType?: string): Promise<AuditRow[]> {
  return ctx.withClient(async (c) => {
    const sql = eventType
      ? `SELECT actor_user_id, target_resource, event_type, outcome, metadata
           FROM audit_log
          WHERE event_type = $1
          ORDER BY ts ASC`
      : `SELECT actor_user_id, target_resource, event_type, outcome, metadata
           FROM audit_log
          ORDER BY ts ASC`;
    const result = eventType
      ? await c.query<AuditRow & { metadata: unknown }>(sql, [eventType])
      : await c.query<AuditRow & { metadata: unknown }>(sql);
    return result.rows.map((r) => ({
      actor_user_id: r.actor_user_id,
      target_resource: r.target_resource,
      event_type: r.event_type,
      outcome: r.outcome,
      metadata:
        typeof r.metadata === 'string'
          ? (JSON.parse(r.metadata) as Record<string, unknown>)
          : (r.metadata as Record<string, unknown>),
    }));
  });
}

/**
 * Read the metadata columns of a provider_keys row.
 *
 * Intentionally omits the bytea columns (ciphertext / nonce / auth_tag)
 * because pg-mem's pg adapter does not round-trip bytea Buffers
 * cleanly under all conditions; the encrypt/decrypt round trip is
 * already validated in `tests/unit/ai/keys.test.ts` against the same
 * `aes-gcm` module these routes use, and against the same
 * `provider_keys` schema.
 */
async function readKeyMeta(provider: string) {
  return ctx.withClient(async (c) => {
    const r = await c.query<{
      provider: string;
      last4: string;
      version: number;
    }>(
      `SELECT provider, last4, version
         FROM provider_keys
        WHERE provider = $1`,
      [provider],
    );
    return r.rows[0];
  });
}

async function countKeyRows(provider: string): Promise<number> {
  return ctx.withClient(async (c) => {
    const r = await c.query<{ count: string }>(
      `SELECT COUNT(*)::text AS count FROM provider_keys WHERE provider = $1`,
      [provider],
    );
    return Number(r.rows[0]?.count ?? 0);
  });
}

// ---------------------------------------------------------------------------
// Auth gates
// ---------------------------------------------------------------------------

describe('admin/provider-keys: authorization', () => {
  it('returns 403 forbidden_role for GET without Authorization header', async () => {
    const res = await makeApp().request('/admin/provider-keys');
    expect(res.status).toBe(403);
    const body = (await res.json()) as { error: { code: string } };
    expect(body.error.code).toBe('forbidden_role');
  });

  it('returns 403 forbidden_role for non-admin user on GET', async () => {
    const res = await makeApp().request('/admin/provider-keys', {
      headers: { Authorization: await userBearer() },
    });
    expect(res.status).toBe(403);
  });

  it('returns 403 forbidden_role for non-admin user on POST and writes no audit row', async () => {
    const res = await makeApp().request('/admin/provider-keys', {
      method: 'POST',
      headers: {
        'Content-Type': 'application/json',
        Authorization: await userBearer(),
      },
      body: JSON.stringify({ provider: 'gemini', key: 'any-key' }),
    });
    expect(res.status).toBe(403);
    expect(await readAuditRows()).toHaveLength(0);
  });

  it('returns 403 forbidden_role for non-admin user on PATCH', async () => {
    const res = await makeApp().request('/admin/provider-keys/gemini', {
      method: 'PATCH',
      headers: {
        'Content-Type': 'application/json',
        Authorization: await userBearer(),
      },
      body: JSON.stringify({ key: 'any-key' }),
    });
    expect(res.status).toBe(403);
  });

  it('returns 403 forbidden_role for non-admin user on DELETE', async () => {
    const res = await makeApp().request('/admin/provider-keys/gemini', {
      method: 'DELETE',
      headers: { Authorization: await userBearer() },
    });
    expect(res.status).toBe(403);
  });
});

// ---------------------------------------------------------------------------
// GET /admin/provider-keys
// ---------------------------------------------------------------------------

describe('GET /admin/provider-keys', () => {
  it('returns an empty list when no keys are stored', async () => {
    const res = await makeApp().request('/admin/provider-keys', {
      headers: { Authorization: await adminBearer() },
    });
    expect(res.status).toBe(200);
    const body = (await res.json()) as { provider_keys: unknown[] };
    expect(body.provider_keys).toEqual([]);
  });

  it('returns masked entries with 8-char fixed mask, last4, version, and created_at', async () => {
    const app = makeApp();
    await app.request('/admin/provider-keys', {
      method: 'POST',
      headers: {
        'Content-Type': 'application/json',
        Authorization: await adminBearer(),
      },
      body: JSON.stringify({
        provider: 'gemini',
        key: 'sk-live-abcdef1234XYZ',
      }),
    });

    const res = await app.request('/admin/provider-keys', {
      headers: { Authorization: await adminBearer() },
    });
    expect(res.status).toBe(200);
    const body = (await res.json()) as {
      provider_keys: Array<{
        provider: string;
        masked: string;
        last4: string;
        version: number;
        created_at: string;
        updated_at: string;
      }>;
    };
    expect(body.provider_keys).toHaveLength(1);
    const entry = body.provider_keys[0]!;
    expect(entry.provider).toBe('gemini');
    expect(entry.masked).toBe('********');
    expect(entry.masked.length).toBe(8);
    // last 4 of "sk-live-abcdef1234XYZ" => "4XYZ"
    expect(entry.last4).toBe('4XYZ');
    expect(entry.version).toBe(1);
    expect(typeof entry.created_at).toBe('string');
    expect(new Date(entry.created_at).toString()).not.toBe('Invalid Date');
  });

  it('omits any plaintext or ciphertext from the masked listing', async () => {
    const app = makeApp();
    const secret = 'super-secret-' + randomBytes(8).toString('hex');
    await app.request('/admin/provider-keys', {
      method: 'POST',
      headers: {
        'Content-Type': 'application/json',
        Authorization: await adminBearer(),
      },
      body: JSON.stringify({ provider: 'groq', key: secret }),
    });

    const res = await app.request('/admin/provider-keys', {
      headers: { Authorization: await adminBearer() },
    });
    const text = await res.text();
    expect(text).not.toContain(secret);
    expect(text).not.toContain('ciphertext');
    expect(text).not.toContain('auth_tag');
    expect(text).not.toContain('nonce');
  });

  it('returns multiple stored keys ordered by canonical provider order', async () => {
    const app = makeApp();
    // Insert directly into the database with safe bytea values to avoid
    // pg-mem's intermittent bytea parsing issues with random ciphertext.
    await ctx.withClient(async (c) => {
      for (const provider of ['cerebras', 'gemini', 'deepseek', 'groq']) {
        const safeBytea = Buffer.from(`fake-${provider}`, 'utf8');
        await c.query(
          `INSERT INTO provider_keys (provider, ciphertext, nonce, auth_tag, last4, version)
           VALUES ($1, $2, $3, $4, $5, 1)`,
          [provider, safeBytea, Buffer.alloc(12, 0), Buffer.alloc(16, 0), '1234'],
        );
      }
    });

    const res = await app.request('/admin/provider-keys', {
      headers: { Authorization: await adminBearer() },
    });
    const body = (await res.json()) as {
      provider_keys: Array<{ provider: string }>;
    };
    expect(body.provider_keys.map((k) => k.provider)).toEqual([
      'gemini',
      'groq',
      'deepseek',
      'cerebras',
    ]);
  });
});

// ---------------------------------------------------------------------------
// POST /admin/provider-keys (create)
// ---------------------------------------------------------------------------

describe('POST /admin/provider-keys', () => {
  it('encrypts and persists a new key and returns 201', async () => {
    const res = await makeApp().request('/admin/provider-keys', {
      method: 'POST',
      headers: {
        'Content-Type': 'application/json',
        Authorization: await adminBearer(),
      },
      body: JSON.stringify({ provider: 'gemini', key: 'plaintext-1234' }),
    });
    expect(res.status).toBe(201);
    const body = (await res.json()) as {
      provider_key: { provider: string; version: number; last4: string; masked: string };
    };
    expect(body.provider_key.provider).toBe('gemini');
    expect(body.provider_key.version).toBe(1);
    expect(body.provider_key.last4).toBe('1234');
    expect(body.provider_key.masked).toBe('********');

    const row = await readKeyMeta('gemini');
    expect(row).toBeDefined();
    expect(row!.version).toBe(1);
    expect(row!.last4).toBe('1234');
  });

  it('writes an audit row containing actor, provider, action=create', async () => {
    await makeApp().request('/admin/provider-keys', {
      method: 'POST',
      headers: {
        'Content-Type': 'application/json',
        Authorization: await adminBearer(),
      },
      body: JSON.stringify({ provider: 'groq', key: 'plain-aaa-bbb' }),
    });

    const audits = await readAuditRows('provider_key_create');
    expect(audits).toHaveLength(1);
    const audit = audits[0]!;
    expect(audit.actor_user_id).toBe(ADMIN_ID);
    expect(audit.target_resource).toBe('provider_key:groq');
    expect(audit.outcome).toBe('success');
    expect(audit.metadata).toMatchObject({
      provider: 'groq',
      action: 'create',
      version: 1,
    });
  });

  it('rejects an empty key with 400 invalid_provider_key and writes no audit row', async () => {
    const res = await makeApp().request('/admin/provider-keys', {
      method: 'POST',
      headers: {
        'Content-Type': 'application/json',
        Authorization: await adminBearer(),
      },
      body: JSON.stringify({ provider: 'gemini', key: '' }),
    });
    expect(res.status).toBe(400);
    const body = (await res.json()) as { error: { code: string; details?: { field?: string } } };
    expect(body.error.code).toBe('invalid_provider_key');
    expect(body.error.details?.field).toBe('key');
    expect(await readAuditRows()).toHaveLength(0);
  });

  it('rejects a key longer than 512 chars', async () => {
    const tooLong = 'a'.repeat(513);
    const res = await makeApp().request('/admin/provider-keys', {
      method: 'POST',
      headers: {
        'Content-Type': 'application/json',
        Authorization: await adminBearer(),
      },
      body: JSON.stringify({ provider: 'gemini', key: tooLong }),
    });
    expect(res.status).toBe(400);
    const body = (await res.json()) as { error: { code: string; details?: { field?: string } } };
    expect(body.error.code).toBe('invalid_provider_key');
    expect(body.error.details?.field).toBe('key');
  });

  it('accepts a key of moderate length (well within bounds)', async () => {
    const exact = 'k'.repeat(256);
    const res = await makeApp().request('/admin/provider-keys', {
      method: 'POST',
      headers: {
        'Content-Type': 'application/json',
        Authorization: await adminBearer(),
      },
      body: JSON.stringify({ provider: 'deepseek', key: exact }),
    });
    expect(res.status).toBe(201);
  });

  it('rejects keys with leading whitespace', async () => {
    const res = await makeApp().request('/admin/provider-keys', {
      method: 'POST',
      headers: {
        'Content-Type': 'application/json',
        Authorization: await adminBearer(),
      },
      body: JSON.stringify({ provider: 'gemini', key: ' has-leading-space' }),
    });
    expect(res.status).toBe(400);
    const body = (await res.json()) as { error: { code: string } };
    expect(body.error.code).toBe('invalid_provider_key');
  });

  it('rejects keys with trailing whitespace', async () => {
    const res = await makeApp().request('/admin/provider-keys', {
      method: 'POST',
      headers: {
        'Content-Type': 'application/json',
        Authorization: await adminBearer(),
      },
      body: JSON.stringify({ provider: 'gemini', key: 'has-trailing-newline\n' }),
    });
    expect(res.status).toBe(400);
  });

  it('rejects an unknown provider', async () => {
    const res = await makeApp().request('/admin/provider-keys', {
      method: 'POST',
      headers: {
        'Content-Type': 'application/json',
        Authorization: await adminBearer(),
      },
      body: JSON.stringify({ provider: 'openai', key: 'plain-1234' }),
    });
    expect(res.status).toBe(400);
    const body = (await res.json()) as { error: { code: string; details?: { field?: string } } };
    expect(body.error.code).toBe('invalid_provider_key');
    expect(body.error.details?.field).toBe('provider');
  });

  it('rejects unknown body fields with 400 (strict schema)', async () => {
    const res = await makeApp().request('/admin/provider-keys', {
      method: 'POST',
      headers: {
        'Content-Type': 'application/json',
        Authorization: await adminBearer(),
      },
      body: JSON.stringify({
        provider: 'gemini',
        key: 'plain-1234',
        mystery: 'no',
      }),
    });
    expect(res.status).toBe(400);
  });

  it('rejects malformed JSON with 400 invalid_provider_key', async () => {
    const res = await makeApp().request('/admin/provider-keys', {
      method: 'POST',
      headers: {
        'Content-Type': 'application/json',
        Authorization: await adminBearer(),
      },
      body: 'not-json',
    });
    expect(res.status).toBe(400);
    const body = (await res.json()) as { error: { code: string } };
    expect(body.error.code).toBe('invalid_provider_key');
  });

  it('returns 409 provider_key_exists when a key for that provider already exists', async () => {
    const app = makeApp();
    const auth = { Authorization: await adminBearer(), 'Content-Type': 'application/json' };

    await app.request('/admin/provider-keys', {
      method: 'POST',
      headers: auth,
      body: JSON.stringify({ provider: 'gemini', key: 'first-key-1' }),
    });
    const res = await app.request('/admin/provider-keys', {
      method: 'POST',
      headers: auth,
      body: JSON.stringify({ provider: 'gemini', key: 'second-key-2' }),
    });
    expect(res.status).toBe(409);
    const body = (await res.json()) as { error: { code: string } };
    expect(body.error.code).toBe('provider_key_exists');

    // Existing row preserved (R4.8 / "leave previously stored unchanged").
    const row = await readKeyMeta('gemini');
    expect(row!.last4).toBe('ey-1');
  });

  it('does not return any plaintext key in the create response body', async () => {
    const secret = 'super-secret-' + randomBytes(10).toString('hex');
    const res = await makeApp().request('/admin/provider-keys', {
      method: 'POST',
      headers: {
        'Content-Type': 'application/json',
        Authorization: await adminBearer(),
      },
      body: JSON.stringify({ provider: 'cerebras', key: secret }),
    });
    expect(res.status).toBe(201);
    const text = await res.text();
    expect(text).not.toContain(secret);
  });
});

// ---------------------------------------------------------------------------
// PATCH /admin/provider-keys/:provider (rotate)
// ---------------------------------------------------------------------------

describe('PATCH /admin/provider-keys/:provider', () => {
  it('rotates the stored ciphertext and increments the version', async () => {
    const app = makeApp();
    const auth = { Authorization: await adminBearer(), 'Content-Type': 'application/json' };

    await app.request('/admin/provider-keys', {
      method: 'POST',
      headers: auth,
      body: JSON.stringify({ provider: 'gemini', key: 'orig-key-aaaa' }),
    });

    const res = await app.request('/admin/provider-keys/gemini', {
      method: 'PATCH',
      headers: auth,
      body: JSON.stringify({ key: 'rotated-bbbb' }),
    });
    expect(res.status).toBe(200);
    const body = (await res.json()) as {
      provider_key: { provider: string; version: number; last4: string };
    };
    expect(body.provider_key.version).toBe(2);
    expect(body.provider_key.last4).toBe('bbbb');

    const after = await readKeyMeta('gemini');
    expect(after!.version).toBe(2);
    expect(after!.last4).toBe('bbbb');
  });

  it('writes an audit row with previous_version, new version, and action=rotate', async () => {
    const app = makeApp();
    const auth = { Authorization: await adminBearer(), 'Content-Type': 'application/json' };

    await app.request('/admin/provider-keys', {
      method: 'POST',
      headers: auth,
      body: JSON.stringify({ provider: 'groq', key: 'orig-key-aaaa' }),
    });
    await app.request('/admin/provider-keys/groq', {
      method: 'PATCH',
      headers: auth,
      body: JSON.stringify({ key: 'rotated-bbbb' }),
    });

    const audits = await readAuditRows('provider_key_rotate');
    expect(audits).toHaveLength(1);
    const audit = audits[0]!;
    expect(audit.actor_user_id).toBe(ADMIN_ID);
    expect(audit.target_resource).toBe('provider_key:groq');
    expect(audit.metadata).toMatchObject({
      provider: 'groq',
      action: 'rotate',
      previous_version: 1,
      version: 2,
    });
  });

  it('produces a strictly increasing version across multiple rotations', async () => {
    const app = makeApp();
    const auth = { Authorization: await adminBearer(), 'Content-Type': 'application/json' };

    await app.request('/admin/provider-keys', {
      method: 'POST',
      headers: auth,
      body: JSON.stringify({ provider: 'deepseek', key: 'k1234' }),
    });
    for (let i = 0; i < 5; i++) {
      await app.request('/admin/provider-keys/deepseek', {
        method: 'PATCH',
        headers: auth,
        body: JSON.stringify({ key: `rot-${i}-1234` }),
      });
    }
    const row = await readKeyMeta('deepseek');
    expect(row!.version).toBe(6);
  });

  it('returns 404 when no key exists for that provider', async () => {
    const res = await makeApp().request('/admin/provider-keys/gemini', {
      method: 'PATCH',
      headers: {
        'Content-Type': 'application/json',
        Authorization: await adminBearer(),
      },
      body: JSON.stringify({ key: 'plain-1234' }),
    });
    expect(res.status).toBe(404);
    const body = (await res.json()) as { error: { code: string } };
    expect(body.error.code).toBe('provider_key_not_found');
  });

  it('rejects rotation with empty key and leaves prior key unchanged', async () => {
    const app = makeApp();
    const auth = { Authorization: await adminBearer(), 'Content-Type': 'application/json' };

    await app.request('/admin/provider-keys', {
      method: 'POST',
      headers: auth,
      body: JSON.stringify({ provider: 'gemini', key: 'orig-key-aaaa' }),
    });
    const before = await readKeyMeta('gemini');

    const res = await app.request('/admin/provider-keys/gemini', {
      method: 'PATCH',
      headers: auth,
      body: JSON.stringify({ key: '' }),
    });
    expect(res.status).toBe(400);
    const body = (await res.json()) as { error: { code: string } };
    expect(body.error.code).toBe('invalid_provider_key');

    const after = await readKeyMeta('gemini');
    expect(after!.version).toBe(1);
    expect(after!.last4).toBe(before!.last4);
  });

  it('rejects rotation with whitespace-padded key', async () => {
    const app = makeApp();
    const auth = { Authorization: await adminBearer(), 'Content-Type': 'application/json' };

    await app.request('/admin/provider-keys', {
      method: 'POST',
      headers: auth,
      body: JSON.stringify({ provider: 'gemini', key: 'orig-key-aaaa' }),
    });
    const res = await app.request('/admin/provider-keys/gemini', {
      method: 'PATCH',
      headers: auth,
      body: JSON.stringify({ key: ' has-leading' }),
    });
    expect(res.status).toBe(400);
  });

  it('rejects rotation against an unknown provider slug', async () => {
    const res = await makeApp().request('/admin/provider-keys/openai', {
      method: 'PATCH',
      headers: {
        'Content-Type': 'application/json',
        Authorization: await adminBearer(),
      },
      body: JSON.stringify({ key: 'plain-1234' }),
    });
    expect(res.status).toBe(400);
    const body = (await res.json()) as { error: { code: string } };
    expect(body.error.code).toBe('invalid_provider_key');
  });
});

// ---------------------------------------------------------------------------
// DELETE /admin/provider-keys/:provider
// ---------------------------------------------------------------------------

describe('DELETE /admin/provider-keys/:provider', () => {
  it('deletes the stored row and writes an audit row', async () => {
    const app = makeApp();
    const auth = { Authorization: await adminBearer(), 'Content-Type': 'application/json' };

    await app.request('/admin/provider-keys', {
      method: 'POST',
      headers: auth,
      body: JSON.stringify({ provider: 'gemini', key: 'plain-1234' }),
    });

    const res = await app.request('/admin/provider-keys/gemini', {
      method: 'DELETE',
      headers: auth,
    });
    expect(res.status).toBe(200);
    const body = (await res.json()) as { deleted: boolean; provider: string };
    expect(body.deleted).toBe(true);
    expect(body.provider).toBe('gemini');

    expect(await countKeyRows('gemini')).toBe(0);

    const audits = await readAuditRows('provider_key_delete');
    expect(audits).toHaveLength(1);
    expect(audits[0]!.actor_user_id).toBe(ADMIN_ID);
    expect(audits[0]!.target_resource).toBe('provider_key:gemini');
    expect(audits[0]!.metadata).toMatchObject({
      provider: 'gemini',
      action: 'delete',
      deleted_version: 1,
    });
  });

  it('returns 404 when no key exists for that provider', async () => {
    const res = await makeApp().request('/admin/provider-keys/gemini', {
      method: 'DELETE',
      headers: { Authorization: await adminBearer() },
    });
    expect(res.status).toBe(404);
    const body = (await res.json()) as { error: { code: string } };
    expect(body.error.code).toBe('provider_key_not_found');
  });

  it('returns 400 invalid_provider_key for unknown provider slug', async () => {
    const res = await makeApp().request('/admin/provider-keys/openai', {
      method: 'DELETE',
      headers: { Authorization: await adminBearer() },
    });
    expect(res.status).toBe(400);
    const body = (await res.json()) as { error: { code: string } };
    expect(body.error.code).toBe('invalid_provider_key');
  });
});
